### ISSUE TITLE
2.31  tree-map 定义

### ISSUE THREAD

**Issue by ljf007** [huangzworks/SICP-answers#10]
http://sicp.readthedocs.org/en/latest/chp2/31.html

注释有问题  定义二  ; 递归处理左右分支

并没有左右分支吧！应该是递归处理 从左至右

**Comment by huangzworks** [comment]
是的，注释里没说正确。

现在已经[修复](https://github.com/huangz1990/SICP-answers/commit/9c66040a8b1558c016ee11c1437908c4d9f295bd)了，感谢提醒！
