### ISSUE TITLE
修复练习 3.16 

### ISSUE THREAD

**Issue by huangzworks** [huangzworks/SICP-answers#6]
http://sicp.readthedocs.org/en/latest/chp3/16.html#comment-771430500

**Comment by darkjh** [comment]
(define x (list 1))
(define y (cons x x))
(define z (cons y y))
(count-pairs z)  ;; 7

以上这样应该可以
x 长度为1
y 长度为3 (两个x, 一个自己)
z的长度是7 (两个y, 一个自己)
一共是三个cons
