### ISSUE TITLE
2.25 你的解答并没有按照题目要求做

### ISSUE THREAD

**Issue by ljf007** [huangzworks/SICP-answers#9]
2.25 你的解答并没有按照题目要求做

要求是使用car和cdr的组合。
(car (cdr (car (cdr (cdr '(1 3 (5 7) 9))))))
(car (car '((7))))
(car (cdr(car (cdr(car (cdr(car (cdr(car (cdr(car (cdr '(1 (2 (3 (4 (5 (6 7)))))) ))))))))))))

**Comment by huangzworks** [comment]
`cxxr` 是 mit-scheme 对于 `car` 和 `cdr` 的变种，它们是等价的。

**Comment by ljf007** [comment]
你的做法和 让你写个reverse，你直接使用库函数是一样的，

在 2013-6-23，21:11，huangz notifications@github.com 写道：

**Comment by huangzworks** [comment]
书本在这道习题之前已经介绍了 `cxxr` ，我看不到任何需要舍近求远的理由。
